version: "3.3"

name: discord-bot
volumes:
  postgres_volume:
services:
  postgres:
    image: postgres:latest
    env_file: .env
    user: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  bot:
    build: .
    env_file: .env
    command: python3 ./run.py
    volumes:
      - ./bot:/home/discord/bot/
    depends_on:
      - postgres
