"""major overhaul

Revision ID: 9136490b3f27
Revises: 
Create Date: 2024-03-19 05:01:54.914444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from datetime import datetime
import pytz


# revision identifiers, used by Alembic.
revision: str = '9136490b3f27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

epoch=datetime(1970, 1, 1,tzinfo=pytz.timezone("Australia/Brisbane"))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dc_course_channels',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('do_not_reset', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id', 'guild_id', 'course_code')
    )
    op.create_table('dc_course_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('auto_delete', sa.Boolean(), nullable=True),
    sa.Column('auto_delete_ignore_admins', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('dc_statistics_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('regexp_primary', sa.String(), nullable=True),
    sa.Column('regexp_secondary', sa.String(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('minor_threshold', sa.Integer(), nullable=True),
    sa.Column('major_threshold', sa.Integer(), nullable=True),
    sa.Column('minor_role_id', sa.BigInteger(), nullable=True),
    sa.Column('major_role_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('dc_course_enrollments',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id', 'guild_id', 'course_code'], ['dc_course_channels.channel_id', 'dc_course_channels.guild_id', 'dc_course_channels.course_code'], ),
    sa.PrimaryKeyConstraint('user_id', 'channel_id', 'guild_id', 'course_code')
    )
    op.drop_table('dc_settings')
    op.alter_column('dc_reminders', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, cycle=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dc_reminders', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('dc_reminders', 'repeat',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('dc_screams', sa.Column('sc_streak_keeper', sa.DateTime(timezone=True), nullable=False,server_default=str(epoch)))
    op.alter_column('dc_screams', 'sc_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dc_screams', 'sc_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dc_screams', 'sc_best_streak',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dc_screams', 'sc_daily',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dc_screams', 'sc_daily',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('dc_screams', 'sc_best_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dc_screams', 'sc_streak',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dc_screams', 'sc_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('dc_screams', 'sc_streak_keeper')
    op.alter_column('dc_reminders', 'repeat',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dc_reminders', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('dc_reminders', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_table('dc_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dc_settings_pkey')
    )
    op.drop_table('dc_course_enrollments')
    op.drop_table('dc_statistics_config')
    op.drop_table('dc_course_config')
    op.drop_table('dc_course_channels')
    # ### end Alembic commands ###
